# Generated by Django 5.2.10 on 2026-01-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('CANCELED', 'Cancelado'), ('FAILED', 'Falha'), ('REVIEW', 'Aguardando Revisão')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
