# Generated by Django 5.2.10 on 2026-01-12 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, verbose_name='Caminho do Arquivo')),
                ('file_hash', models.CharField(max_length=64, unique=True, verbose_name='Hash do Arquivo')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('carrier', models.CharField(max_length=100, verbose_name='Operadora')),
                ('month', models.CharField(max_length=20, verbose_name='Mês')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número da Fatura')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SUCCESS', 'Sucesso'), ('FAILED', 'Falha'), ('SKIPPED', 'Pulados (Duplicado)')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_source', to='reports.report')),
            ],
            options={
                'verbose_name': 'Importação de Fatura',
                'verbose_name_plural': 'Importações de Faturas',
                'ordering': ['-created_at'],
            },
        ),
    ]
