# Generated by Django 5.2.10 on 2026-01-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceimport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('SUCCESS', 'Sucesso'), ('FAILED', 'Falha'), ('SKIPPED', 'Pulados (Duplicado)'), ('PENDING_REVIEW', 'Aguardando Revisão')], default='PENDING', max_length=20),
        ),
    ]
