# Generated by Django 5.2.10 on 2026-01-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoiceimport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceimport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/', verbose_name='Arquivo PDF'),
        ),
    ]
