# Generated by Django 5.2.10 on 2026-01-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoiceimport_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceimport',
            name='confidence_score',
            field=models.IntegerField(default=0, help_text='0-100 score of parsing confidence', verbose_name='Confiabilidade'),
        ),
    ]
