# Generated by Django 5.2.10 on 2026-01-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoiceimport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceimport',
            name='error_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Erro'),
        ),
        migrations.AlterField(
            model_name='invoiceimport',
            name='status',
            field=models.CharField(choices=[('INBOX', 'Caixa de Entrada'), ('PROCESSING', 'Processando'), ('OCR_RUNNING', 'OCR em Execução'), ('PENDING', 'Pendente'), ('SUCCESS', 'Sucesso'), ('FAILED', 'Falha'), ('SKIPPED', 'Pulados (Duplicado)'), ('PENDING_REVIEW', 'Aguardando Revisão')], default='PENDING', max_length=20),
        ),
    ]
