# Generated by Django 5.2.10 on 2026-01-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('GESTOR', 'Gestor'), ('ANALISTA', 'Analista'), ('VISUALIZADOR', 'Visualizador')], default='VISUALIZADOR', max_length=20, verbose_name='Função'),
        ),
    ]
