# Generated by Django 5.2.10 on 2026-01-13 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('IMPORT', 'Importação'), ('REPROCESS', 'Reprocessamento'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('APPROVE', 'Aprovação'), ('REJECT', 'Rejeição'), ('EXPORT', 'Download/Exportação')], max_length=20, verbose_name='Ação')),
                ('entity', models.CharField(max_length=100, verbose_name='Entidade')),
                ('entity_id', models.CharField(max_length=100, verbose_name='ID da Entidade')),
                ('before_state', models.JSONField(blank=True, null=True, verbose_name='Estado Anterior')),
                ('after_state', models.JSONField(blank=True, null=True, verbose_name='Estado Atual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
